# Generated by Django 3.0.5 on 2020-05-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewProject',
            fields=[
                ('ProjectName', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Project_Name')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManager.accountModel')),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.AddNewProject')),
            ],
        ),
        migrations.CreateModel(
            name='BugSheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('Defect_Id', models.CharField(blank=True, max_length=500, null=True)),
                ('project_version', models.CharField(max_length=500)),
                ('Browser', models.CharField(max_length=500)),
                ('Url_of_page', models.URLField()),
                ('Status', models.CharField(blank=True, choices=[('New', 'New'), ('Reopen', 'Reopen'), ('Closed', 'Closed')], max_length=500, null=True)),
                ('TimesReopened', models.IntegerField(blank=True, default=0, null=True)),
                ('Priority', models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Highest', 'Highest')], max_length=500)),
                ('Defect_desc', models.CharField(max_length=500)),
                ('Steps_to_Reproduce', models.CharField(max_length=500)),
                ('Attachment', models.ImageField(blank=True, max_length=255, null=True, upload_to='screenshots/%Y.%m.%d/')),
                ('Date_of_finding', models.DateField()),
                ('Resolution_Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Solved', 'Solved')], max_length=500, null=True)),
                ('Date_of_resolving', models.DateField(blank=True, null=True)),
                ('Developer_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Reopen_Reason', models.CharField(blank=True, max_length=500, null=True)),
                ('Developer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Developer', to='accountManager.accountModel')),
                ('Project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.AddNewProject')),
                ('Tester_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tester', to='accountManager.accountModel')),
            ],
        ),
    ]
