# Generated by Django 3.0.5 on 2020-05-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0003_auto_20200507_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='changelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('Defect_Id', models.CharField(blank=True, max_length=500, null=True)),
                ('Project_name', models.CharField(blank=True, max_length=500, null=True)),
                ('project_version', models.CharField(max_length=500)),
                ('Browser', models.CharField(max_length=500)),
                ('Url_of_page', models.URLField()),
                ('Status', models.CharField(blank=True, choices=[('New', 'New'), ('Reopen', 'Reopen'), ('Closed', 'Closed')], max_length=500, null=True)),
                ('TimesReopened', models.IntegerField(blank=True, default=0, null=True)),
                ('Priority', models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Highest', 'Highest')], max_length=500)),
                ('Defect_desc', models.TextField()),
                ('Steps_to_Reproduce', models.CharField(max_length=500)),
                ('Date_of_finding', models.DateField()),
                ('Tester_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Developer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Resolution_Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Solved', 'Solved')], max_length=500, null=True)),
                ('Date_of_resolving', models.DateField(blank=True, null=True)),
                ('Developer_comments', models.TextField(blank=True, null=True)),
                ('Reopen_Reason', models.TextField(blank=True, null=True)),
                ('Attachment', models.ImageField(blank=True, max_length=255, null=True, upload_to='screenshots/%Y.%m.%d/')),
            ],
        ),
    ]
