# Generated by Django 3.0.5 on 2020-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_changelogs_type_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsheetmodel',
            name='Date_of_finding',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bugsheetmodel',
            name='Date_of_resolving',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelogs',
            name='Date_of_finding',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='changelogs',
            name='Date_of_resolving',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
