# Generated by Django 3.0.5 on 2020-05-22 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0006_auto_20200522_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsheetmodel',
            name='Browser',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
