# Generated by Django 3.0.6 on 2021-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0007_auto_20200522_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugSheetModelextraimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachment', models.ImageField(blank=True, max_length=255, null=True, upload_to='screenshots/%Y.%m.%d/')),
                ('Date_of_finding', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bugsheetmodel',
            name='Resolution_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('Skip', 'Skip'), ('Closed', 'Closed')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bugsheetmodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Reopen', 'Reopen'), ('Skip', 'Skip'), ('Solved', 'Solved'), ('Closed', 'Closed')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='changelogs',
            name='Resolution_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('Skip', 'Skip'), ('Closed', 'Closed')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='changelogs',
            name='Status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Reopen', 'Reopen'), ('Skip', 'Skip'), ('Solved', 'Solved'), ('Closed', 'Closed')], max_length=500, null=True),
        ),
    ]
