# Generated by Django 3.0.5 on 2020-05-06 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='masterPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterPass', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='accountModel',
            fields=[
                ('UserType', models.CharField(choices=[('developer', 'developer'), ('tester', 'tester')], max_length=500)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bugCount', models.IntegerField(default=0)),
                ('projectCount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
