# Generated by Django 3.0.5 on 2020-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordResetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('guid', models.CharField(max_length=500)),
            ],
        ),
    ]
